export class Table {
    // Table constants
    static readonly BASE = 0x42415345; // Baseline data [OpenType]
    static readonly CFF = 0x43464620; // PostScript font program (compact font format) [PostScript]
    static readonly CFF2 = 0x43464632; // Compact Font Format 2.0
    static readonly DSIG = 0x44534947; // Digital signature
    static readonly EBDT = 0x45424454; // Embedded bitmap data
    static readonly EBLC = 0x45424c43; // Embedded bitmap location data
    static readonly EBSC = 0x45425343; // Embedded bitmap scaling data
    static readonly COLR = 0x434f4c52; // Color glyph layers
    static readonly CPAL = 0x4350414c; // Color palette
    static readonly SVG = 0x53564720;  // SVG glyph data
    static readonly gvar = 0x67766172; // Glyph variations
    static readonly GDEF = 0x47444546; // Glyph definition data [OpenType]
    static readonly GPOS = 0x47504f53; // Glyph positioning data [OpenType]
    static readonly GSUB = 0x47535542; // Glyph substitution data [OpenType]
    static readonly JSTF = 0x4a535446; // Justification data [OpenType]
    static readonly LTSH = 0x4c545348; // Linear threshold table
    static readonly MMFX = 0x4d4d4658; // Multiple master font metrics [PostScript]
    static readonly MMSD = 0x4d4d5344; // Multiple master supplementary data [PostScript]
    static readonly OS_2 = 0x4f532f32; // OS/2 and Windows specific metrics [r]
    static readonly PCLT = 0x50434c54; // PCL5
    static readonly VDMX = 0x56444d58; // Vertical Device Metrics table
    static readonly cmap = 0x636d6170; // character to glyph mapping [r]
    static readonly cvt = 0x63767420; // Control Value Table
    static readonly fpgm = 0x6670676d; // font program
    static readonly fvar = 0x66766172; // Apple's font variations table [PostScript]
    static readonly gasp = 0x67617370; // grid-fitting and scan conversion procedure (grayscale)
    static readonly glyf = 0x676c7966; // glyph data [r]
    static readonly hdmx = 0x68646d78; // horizontal device metrics
    static readonly head = 0x68656164; // font header [r]
    static readonly hhea = 0x68686561; // horizontal header [r]
    static readonly hmtx = 0x686d7478; // horizontal metrics [r]
    static readonly kern = 0x6b65726e; // kerning
    static readonly loca = 0x6c6f6361; // index to location [r]
    static readonly maxp = 0x6d617870; // maximum profile [r]
    static readonly pName = 0x6e616d65; // naming table [r]
    static readonly prep = 0x70726570; // CVT Program
    static readonly post = 0x706f7374; // PostScript information [r]
    static readonly vhea = 0x76686561; // Vertical Metrics header
    static readonly vmtx = 0x766d7478; // Vertical Metrics

    // Platform IDs
    static readonly platformAppleUnicode = 0;
    static readonly platformMacintosh = 1;
    static readonly platformISO = 2;
    static readonly platformMicrosoft = 3;

    // Microsoft Encoding IDs
    static readonly encodingUndefined = 0;
    static readonly encodingUGL = 1;

    // Macvarosh Encoding IDs
    static readonly encodingRoman = 0;
    static readonly encodingJapanese = 1;
    static readonly encodingChinese = 2;
    static readonly encodingKorean = 3;
    static readonly encodingArabic = 4;
    static readonly encodingHebrew = 5;
    static readonly encodingGreek = 6;
    static readonly encodingRussian = 7;
    static readonly encodingRSymbol = 8;
    static readonly encodingDevanagari = 9;
    static readonly encodingGurmukhi = 10;
    static readonly encodingGujarati = 11;
    static readonly encodingOriya = 12;
    static readonly encodingBengali = 13;
    static readonly encodingTamil = 14;
    static readonly encodingTelugu = 15;
    static readonly encodingKannada = 16;
    static readonly encodingMalayalam = 17;
    static readonly encodingSinhalese = 18;
    static readonly encodingBurmese = 19;
    static readonly encodingKhmer = 20;
    static readonly encodingThai = 21;
    static readonly encodingLaotian = 22;
    static readonly encodingGeorgian = 23;
    static readonly encodingArmenian = 24;
    static readonly encodingMaldivian = 25;
    static readonly encodingTibetan = 26;
    static readonly encodingMongolian = 27;
    static readonly encodingGeez = 28;
    static readonly encodingSlavic = 29;
    static readonly encodingVietnamese = 30;
    static readonly encodingSindhi = 31;
    static readonly encodingUnvarerp = 32;

    // ISO Encoding IDs
    static readonly encodingASCII = 0;
    static readonly encodingISO10646 = 1;
    static readonly encodingISO8859_1 = 2;

    // Microsoft Language IDs
    static readonly languageSQI = 0x041c;
    static readonly languageEUQ = 0x042d;
    static readonly languageBEL = 0x0423;
    static readonly languageBGR = 0x0402;
    static readonly languageCAT = 0x0403;
    static readonly languageSHL = 0x041a;
    static readonly languageCSY = 0x0405;
    static readonly languageDAN = 0x0406;
    static readonly languageNLD = 0x0413;
    static readonly languageNLB = 0x0813;
    static readonly languageENU = 0x0409;
    static readonly languageENG = 0x0809;
    static readonly languageENA = 0x0c09;
    static readonly languageENC = 0x1009;
    static readonly languageENZ = 0x1409;
    static readonly languageENI = 0x1809;
    static readonly languageETI = 0x0425;
    static readonly languageFIN = 0x040b;
    static readonly languageFRA = 0x040c;
    static readonly languageFRB = 0x080c;
    static readonly languageFRC = 0x0c0c;
    static readonly languageFRS = 0x100c;
    static readonly languageFRL = 0x140c;
    static readonly languageDEU = 0x0407;
    static readonly languageDES = 0x0807;
    static readonly languageDEA = 0x0c07;
    static readonly languageDEL = 0x1007;
    static readonly languageDEC = 0x1407;
    static readonly languageELL = 0x0408;
    static readonly languageHUN = 0x040e;
    static readonly languageISL = 0x040f;
    static readonly languageITA = 0x0410;
    static readonly languageITS = 0x0810;
    static readonly languageLVI = 0x0426;
    static readonly languageLTH = 0x0427;
    static readonly languageNOR = 0x0414;
    static readonly languageNON = 0x0814;
    static readonly languagePLK = 0x0415;
    static readonly languagePTB = 0x0416;
    static readonly languagePTG = 0x0816;
    static readonly languageROM = 0x0418;
    static readonly languageRUS = 0x0419;
    static readonly languageSKY = 0x041b;
    static readonly languageSLV = 0x0424;
    static readonly languageESP = 0x040a;
    static readonly languageESM = 0x080a;
    static readonly languageESN = 0x0c0a;
    static readonly languageSVE = 0x041d;
    static readonly languageTRK = 0x041f;
    static readonly languageUKR = 0x0422;

    // Macvarosh Language IDs
    static readonly languageEnglish = 0;
    static readonly languageFrench = 1;
    static readonly languageGerman = 2;
    static readonly languageItalian = 3;
    static readonly languageDutch = 4;
    static readonly languageSwedish = 5;
    static readonly languageSpanish = 6;
    static readonly languageDanish = 7;
    static readonly languagePortuguese = 8;
    static readonly languageNorwegian = 9;
    static readonly languageHebrew = 10;
    static readonly languageJapanese = 11;
    static readonly languageArabic = 12;
    static readonly languageFinnish = 13;
    static readonly languageGreek = 14;
    static readonly languageIcelandic = 15;
    static readonly languageMaltese = 16;
    static readonly languageTurkish = 17;
    static readonly languageYugoslavian = 18;
    static readonly languageChinese = 19;
    static readonly languageUrdu = 20;
    static readonly languageHindi = 21;
    static readonly languageThai = 22;

    // Name IDs
    static readonly nameCopyrightNotice = 0;
    static readonly nameFontFamilyName = 1;
    static readonly nameFontSubfamilyName = 2;
    static readonly nameUniqueFontIdentifier = 3;
    static readonly nameFullFontName = 4;
    static readonly nameVersionString = 5;
    static readonly namePostscriptName = 6;
    static readonly nameTrademark = 7;
}
